blank_issues_enabled: false
contact_links:
  - name: pheno-tracing Discussions
    url: https://github.com/KooshaPari/pheno-tracing/discussions
    about: Please ask and answer questions about usage and design here.
